-- begin EMPLOYEETESTING_EMPLOYEE
alter table EMPLOYEETESTING_EMPLOYEE add constraint FK_EMPLOYEETESTING_EMPLOYEE_IMAGE_FILE foreign key (IMAGE_FILE_ID) references SYS_FILE(ID)^
-- end EMPLOYEETESTING_EMPLOYEE
